version: '3'

services:
  web:
    build: .
    ports:
      - "8000:80"
    depends_on:
      - db

  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
      MYSQL_ROOT_PASSWORD: symfony
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"