#index:
#    path: /
#    controller: App\Controller\DefaultController::index

create_supplier:
    path: /supplier
    controller: App\Controller\SupplierController::create
    methods: [GET, POST]

index_supplier:
    path: /supplier/index
    controller: App\Controller\SupplierController::index
    methods: [GET]