<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCPXTS1t\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCPXTS1t/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCPXTS1t.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCPXTS1t\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCPXTS1t\App_KernelDevDebugContainer([
    'container.build_hash' => 'CPXTS1t',
    'container.build_id' => '262be604',
    'container.build_time' => 1706783516,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCPXTS1t');
